
## Service Account 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  namespace: application
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: application

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    prometheus: application
  name: gmp-application-pm

spec:
  podMetricsEndpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app: prom-example

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    prometheus: application
  name: service-monitor

spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      app: prom-example

---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: rahul
spec:
  serviceMonitorNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: application
  podMonitorNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: application
  podMonitorSelector:
    matchLabels:
      prometheus: application
  serviceMonitorSelector:
    matchLabels:
      prometheus: application
  resources:
    requests:
      memory: 400Mi
  serviceAccountName: prometheus
